---
title: 가장 빨리 만나는 코어 자바 9 정리 - 5장
date: 2020-05-24
tag: [Study]
---

## 5장: 예외, 단정, 로깅

<br>

- 예외 던지기  
   문제가 되는 상황에서 문제를 고치려기보다는 적절한 에러를 던지는 것이 좋다.

    ```java
    if (low > high) {
      throw new IllegalArgumentException();
    }

    // Exception java.lang.IllegalArgumentException at (#4:1)
    ```

<br>

- 프로그래머가 보고하는 예외는 `검사 예외`와 `비검사 예외` 두 가지로 나눌 수 있다.  
검사 예외는 실패를 예상하는 상황에서 사용되며, 비검사 예외는 피할 수 없는 외부 위험 요소가 아니라 프로그래머가 만든 논리 오류를 나타낸다. 검사 예외의 대표적인 예는 입출력이 있고, 비검사 예외의 대표적인 예는 NullPointerException이 있다. 각각 예외에 대해서는 상황에 맞는 예외 클래스를 사용하면 된다. 하지만 만약 적절한 예외클래스가 없는 경우 기존 예외 클래스를 확장해서 만들 수 있다.

    ```java
    public class CustomException extends IOException {
      public CustomException () {} // 인수 없는 생성자
      public CustomException (String message) {
        super(message);
      }
    }
    ```

<br>

- try - catch  
   try문 안에서 발생한 예외를 catch가 잡아서 처리해준다.

    ```java
    // 기본 형태
    try {
      statement
    } catch (ExceptionClass ex) {
      handler
    }

    // 서로 다른 예외 클래스에 대응하는 핸들러
    try {
      statement
    } catch (ExceptionClass1 ex) {
      handler1
    } catch (ExceptionClass2 ex) {
      handler2
    } catch (ExceptionClass3 ex) {
      handler3
    } catch (ExceptionClass4 | ExceptionClass5 | ExceptionClass6) {
      handler4
    }
    ```

<br>

- try - finally  
   try문의 예외 발생 여부와 관계 없이 무조건적으로 실행해야 할 작업이 있는 경우 finally문을 사용한다. finally 문에서는 예외를 던지지 않아야 한다. 왜냐하면 try 문 안에서 예외가 발생해도 finally 문에서의 예외가 이를 덮어씌워 버리기 때문이다. 같은 이유로 finally 문에서는 return을 하면 안된다. 이 return이 반환 값을 교체해버리기 때문이다.

    ```java
    // 기본 형태
    try {
      statement
    } finally {
      finishing operation
    }

    // try - catch - finally로도 사용할 수 있다.
    try {
      in = File.newBufferedReader(path, StandardCharsets.UTF_8);
    } catch (IOException ex) {
      System.err.println(ex);
    } finally {
      if (in != null) {
        in.close();
      }
    }
    ```

<br>

- try - with - resourses  
   Java7 이전에는 try-catch-finally로 자원을 해제해주어야 했으나 Java7부터 try-with-resources 구문을 지원해주어 이제 쉽게 자원을 해제할 수 있게되었다. 다음은 try-catch-finally를 try-with-resources로 바꾼 것이다. 두 개 모두 실행결과는 동일하다.

    ``` java
    // try-catch-finally
    FileInputStream is = null;
    BufferedInputStream bis = null;
    try {
        is = new FileInputStream("file.txt");
        bis = new BufferedInputStream(is);
        int data = -1;
        while((data = bis.read()) != -1){
            System.out.print((char) data);
        }
    } catch (IOException e) {
      e.printStackTrace();
    } finally {
        // close resources
        if (is != null) is.close();
        if (bis != null) bis.close();
    }

    // try-with-resources
    try (
        FileInputStream is = new FileInputStream("file.txt");
        BufferedInputStream bis = new BufferedInputStream(is)
    ) {
        int data = -1;
        while ((data = bis.read()) != -1) {
            System.out.print((char) data);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    ```

    위에서 보이듯 try-with-resources를 사용하면 훨씰 코드가 간결하며, 실수로 close를 빼먹을 위험이 줄어든다.  
    주의해야할 점은 try-with-resources가 모든 객체의 close()를 호출해주지는 않는다는 것이다. AutoCloseable을 implements한 객체만 close()가 호출된다. 위의 예시 FileInputStream과 BufferdInputStream은 AutoCloseable을 implements한 객체이므로 close()가 호출되며, 만약 내가 만든 클래스가 close()되고 싶다면, AutoCloseable을 implements 해야한다.

<br>

- 예외 다시 던지기  
   예외가 발생할 때 무슨 일을 해야할 지 모르더라도 실패를 로그로 기록하고 싶을 수 있다. 이 경우에는 로그를 기록한 뒤 에러를 다시 던져서 적합한 예외 핸들러가 다룰 수 있게 해야 한다.

    ```java
    try {
      statement
    } catch (Exception ex) {
      logger.log(level, message, ex);
      throw ex;
    }

    // 예외를 연쇄할 수도 있다.
    try {
      statemet
    } catch (SQLException ex) {
      throw new ServletException("Database Error", ex);
    }
    ```

<br>

- 단정

    ```java
    // 기본 형태 assert condition : expression
    int x = 10;
    assert x < 10 : "Assert Error!"
    => AssertionError : Assert Error!
    ```

<br>

- 로깅

    ```java
    import java.util.logging.*;

    Logger.getGlobal().info("Global logger info");
    Logger logger = Logger.getLogger("com.practice.App");
    logger.info("Custom logger info");
    logger.warning("Custom logger warning");

    /*
    5월 28, 2020 1:57:08 오후 com.prac.App main
    INFO: Global logger info
    5월 28, 2020 1:57:08 오후 com.prac.App main
    INFO: Custom logger info
    5월 28, 2020 1:57:08 오후 com.prac.App main
    WARNING: Custom logger warning
    */
    ```
